// Andead.SmartHome.Presentation.API/src/components/log-events.tsx
﻿import { Component } from 'react';
import * as signalR from '@microsoft/signalr';

interface IHubProps {
    hubUrl: string;
    onNewEvent: Function;
}

export default class LogEvents extends Component<IHubProps> {
    componentDidMount() {
        let connection = new signalR.HubConnectionBuilder().withUrl(this.props.hubUrl).build();

        connection.on('newEvent', (...args: any[]) => this.props.onNewEvent(...args));

        connection.start()
            .then(() => console.log(`Connected to hub`))
            .catch(() => console.log(`Can't connect to hub!`));
    }

    render() {
        return null;
    }
}

// Andead.SmartHome.Presentation.API/src/app/log-events/log-events.component.ts
import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import * as signalR from '@microsoft/signalr';

@Component({
    selector: 'log-events',
    templateUrl: './log-events.component.html',
    styleUrls: ['./log-events.component.scss']
})
export class LogEventsComponent implements OnInit {
    @Input() hubUrl: string;
    @Output() onNewEvent: EventEmitter<any[]> = new EventEmitter<any[]>();

    constructor() { }

    ngOnInit(): void {
        if (!this.hubUrl || !this.onNewEvent)
            return;

        let connection = new signalR.HubConnectionBuilder()
            .withUrl(this.hubUrl)
            .build();

        connection.on('newEvent', (...args: any[]) => {
            this.onNewEvent.emit([...args]);
        });

        connection.start()
            .then(() => console.log(`Connected to hub`))
            .catch(() => console.log(`Can't connect to hub!`));
    }
}
